apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-gke
        image: gcr.io/qwiklabs-gcp-03-8d3de33afb85/gcpdevops:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "gke-service"
  namespace: "gcp-devops"
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector:
    app: "gcp"
  type: "LoadBalancer"
